services:
  qdrant-server:
    image: qdrant/qdrant:v1.8.4
    container_name: qdrant
    restart: unless-stopped
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./volumes/qdrant_storage:/qdrant/storage:z
    healthcheck:
      test: ["CMD-SHELL", "/bin/bash -c ':> /dev/tcp/0.0.0.0/6333'"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - qdrant-network

networks:
  qdrant-network:
    driver: bridge

volumes:
  qdrant_storage:
